### ISSUE TITLE
"delta_actions" key in the embeddings dataset

### ISSUE THREAD

**Issue by suessmann** [AGI-Labs/toto_benchmark#5]
Hi!

I am wondering what "delta_actions" key means? This key for sure exists in the `pouring_parsed_with_embeddings_moco_conv5.pkl` file.

**Comment by gaoyuezhou** [comment]
Hi,

Thank you for your question. The "delta_actions" key gives the robot action in delta joint angles instead of absolute joint angles. This benefits some reinforcement learning algorithms according to our experience. It contains equivalent information as the "actions" key. Hope this helps and let us know if you have additional questions!

**Comment by suessmann** [comment]
Thanx for clarifications!
