### ISSUE TITLE
Unable to download the scooping dataset

### ISSUE THREAD

**Issue by sindhu-pr** [AGI-Labs/toto_benchmark#8]
I am unable to download the scooping dataset from google cloud. I cannot pay for the account. The one shared on google drive is corrupted. Please let me know if there is an easier way to download it, have tried the above two methods multiple times and it has become frustrating to keep waiting for the dataset.

**Comment by gaoyuezhou** [comment]
Hi,

You don't need to pay for the account in order to download the data from google cloud bucket. Please access the data [here](https://console.cloud.google.com/storage/browser/toto-dataset) as provided in the Readme and download the folder `cloud-data-scooping/` to get started. Once you click download, you should see this instruction to download the data from your terminal:
```
gsutil -m cp -r \
  "gs://toto-dataset/cloud-data-scooping" \
  .
```
Let me know if this solves the issue. Thank you.

**Comment by kunimatsu-tri** [comment]
Hi,

I tried that command and then got `AccessDeniedException`. Any idea?

**Comment by gaoyuezhou** [comment]
Hi,

Thank you for your question. We tried to recreate the issue but we didn't encounter the `AccessDeniedException` error. Maybe check if your gcloud has been initialized property and whether you have authenticated with your account? You may find this page helpful: https://cloud.google.com/storage/docs/gsutil_install.

Let us know if you have additional questions. Thanks!
